spring.application.name=Resume_Builder
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Email Configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=shreshtabhatnagar@gmail.com
#Cloudinary information


cloudinary.cloud_name=dkh0nvjr0
cloudinary.api_key=115744672729672
cloudinary.api_secret=-o09tDDriLVpw1iYL-1A-k682ns

app.base.url=https://resume-builder-542s.onrender.com
#Application info

#Jwt Configuration
jwt.secret=your-secret-key-here-change-this-in-production-with-more-secure-and-complicated-key
jwt.expiration=604800000

#Rozarpay Configuration
razorpay.key.id=rzp_test_SsmzHh3W6AJn3w 
razorpay.key.secret=uyuPqQnQIMwno2rpvPQ89hTT